version: "3.9"
services:

  monitor:
    image: ipfs-monitor
    container_name: monitor
    ports:
      - "3000:3000"
      - "3100:3100"

  controller:
    image: controller-node
    container_name: controller
    environment:
      HOST_NAME: controller

  node0:
    image: ipfs-node
    container_name: node0
    environment:
      HOST_NAME: node0
      SERVER_PORT: 5000
      GATEWAY_PORT: 8080
      P2P_PORT: 4000
      AGENT_HOST: node0
      AGENT_PORT: 3030

  node1:
    image: ipfs-node
    container_name: node1
    environment:
      HOST_NAME: node1
      SERVER_PORT: 5001
      GATEWAY_PORT: 8081
      P2P_PORT: 4001
      AGENT_HOST: node1
      AGENT_PORT: 3031

  node2:
    image: ipfs-node
    container_name: node2
    environment:
      HOST_NAME: node2
      SERVER_PORT: 5002
      GATEWAY_PORT: 8082
      P2P_PORT: 4002
      AGENT_HOST: node2
      AGENT_PORT: 3032


